-- CreateTable
CREATE TABLE `accounts` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `salt` VARCHAR(191) NULL DEFAULT '',
    `premdays` INTEGER NULL DEFAULT 0,
    `lastday` INTEGER NULL DEFAULT 0,
    `email` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NULL DEFAULT '',
    `blocked` BOOLEAN NULL DEFAULT false,
    `warnings` INTEGER NULL DEFAULT 0,
    `group_id` INTEGER NULL DEFAULT 1,
    `page_access` INTEGER NULL,
    `web_lastlogin` INTEGER NULL DEFAULT 0,
    `web_flags` INTEGER NULL DEFAULT 0,
    `email_hash` VARCHAR(191) NULL DEFAULT '',
    `email_verified` BOOLEAN NULL DEFAULT false,
    `email_new` VARCHAR(191) NULL,
    `email_new_time` INTEGER NULL,
    `rlname` VARCHAR(191) NULL,
    `location` VARCHAR(191) NULL,
    `country` VARCHAR(191) NOT NULL DEFAULT '',
    `created` INTEGER NULL,
    `email_code` VARCHAR(191) NULL,
    `email_next` INTEGER NULL DEFAULT 0,
    `premium_points` INTEGER NULL DEFAULT 0,
    `nickname` VARCHAR(191) NULL,
    `avatar` VARCHAR(191) NULL,
    `about_me` VARCHAR(191) NULL,
    `vote` INTEGER NULL DEFAULT 0,
    `premium_points_used` INTEGER NULL DEFAULT 0,

    UNIQUE INDEX `accounts_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `world_id` INTEGER NOT NULL,
    `group_id` INTEGER NOT NULL DEFAULT 1,
    `account_id` VARCHAR(191) NOT NULL,
    `level` INTEGER NOT NULL DEFAULT 1,
    `vocation` INTEGER NOT NULL DEFAULT 0,
    `health` INTEGER NOT NULL DEFAULT 150,
    `healthmax` INTEGER NOT NULL DEFAULT 150,
    `experience` BIGINT NOT NULL DEFAULT 0,
    `lookbody` INTEGER NOT NULL DEFAULT 0,
    `lookfeet` INTEGER NOT NULL DEFAULT 0,
    `lookhead` INTEGER NOT NULL DEFAULT 0,
    `looklegs` INTEGER NOT NULL DEFAULT 0,
    `looktype` INTEGER NOT NULL DEFAULT 136,
    `lookaddons` INTEGER NOT NULL DEFAULT 0,
    `lookmount` INTEGER NOT NULL DEFAULT 0,
    `maglevel` INTEGER NOT NULL DEFAULT 0,
    `mana` INTEGER NOT NULL DEFAULT 0,
    `manamax` INTEGER NOT NULL DEFAULT 0,
    `manaspent` INTEGER NOT NULL DEFAULT 0,
    `soul` INTEGER NOT NULL DEFAULT 0,
    `town_id` INTEGER NOT NULL DEFAULT 0,
    `posx` INTEGER NOT NULL DEFAULT 0,
    `posy` INTEGER NOT NULL DEFAULT 0,
    `posz` INTEGER NOT NULL DEFAULT 0,
    `conditions` LONGBLOB NOT NULL,
    `cap` INTEGER NOT NULL DEFAULT 0,
    `sex` INTEGER NOT NULL DEFAULT 0,
    `lastlogin` BIGINT NOT NULL DEFAULT 0,
    `lastip` INTEGER NOT NULL DEFAULT 0,
    `save` BOOLEAN NOT NULL DEFAULT true,
    `skull` INTEGER NOT NULL DEFAULT 0,
    `skulltime` INTEGER NOT NULL DEFAULT 0,
    `rank_id` INTEGER NOT NULL DEFAULT 0,
    `guildnick` VARCHAR(191) NOT NULL DEFAULT '',
    `lastlogout` BIGINT NOT NULL DEFAULT 0,
    `blessings` INTEGER NOT NULL DEFAULT 0,
    `pvp_blessing` BOOLEAN NOT NULL DEFAULT false,
    `balance` BIGINT NOT NULL DEFAULT 0,
    `stamina` BIGINT NOT NULL DEFAULT 151200000,
    `direction` INTEGER NOT NULL DEFAULT 2,
    `loss_experience` INTEGER NOT NULL DEFAULT 100,
    `loss_mana` INTEGER NOT NULL DEFAULT 100,
    `loss_skills` INTEGER NOT NULL DEFAULT 100,
    `loss_containers` INTEGER NOT NULL DEFAULT 100,
    `loss_items` INTEGER NOT NULL DEFAULT 100,
    `premend` INTEGER NOT NULL DEFAULT 0,
    `online` BOOLEAN NOT NULL DEFAULT false,
    `marriage` INTEGER NOT NULL DEFAULT 0,
    `promotion` INTEGER NOT NULL DEFAULT 0,
    `deleted` INTEGER NOT NULL DEFAULT 0,
    `description` VARCHAR(191) NOT NULL DEFAULT '',
    `old_name` VARCHAR(191) NULL,
    `hidden` BOOLEAN NOT NULL DEFAULT false,
    `worldtransfer` INTEGER NULL,
    `created` INTEGER NULL,
    `nick_verify` INTEGER NULL,
    `comment` VARCHAR(191) NULL,
    `rep` INTEGER NOT NULL DEFAULT 0,
    `ip` VARCHAR(191) NOT NULL DEFAULT '0',
    `offlinetraining_time` INTEGER NOT NULL DEFAULT 43200,
    `offlinetraining_skill` INTEGER NOT NULL DEFAULT -1,
    `broadcasting` INTEGER NOT NULL DEFAULT 0,
    `viewers` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `players_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `players` ADD CONSTRAINT `players_account_id_fkey` FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
