-- CreateTable
CREATE TABLE "players" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "world_id" INTEGER NOT NULL,
    "group_id" INTEGER NOT NULL,
    "account_id" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "vocation" INTEGER NOT NULL,
    "health" INTEGER NOT NULL,
    "healthmax" INTEGER NOT NULL,
    "experience" BIGINT NOT NULL,
    "lookbody" INTEGER NOT NULL,
    "lookfeet" INTEGER NOT NULL,
    "lookhead" INTEGER NOT NULL,
    "looklegs" INTEGER NOT NULL,
    "looktype" INTEGER NOT NULL,
    "lookaddons" INTEGER NOT NULL,
    "lookmount" INTEGER NOT NULL,
    "maglevel" INTEGER NOT NULL,
    "mana" INTEGER NOT NULL,
    "manamax" INTEGER NOT NULL,
    "manaspent" INTEGER NOT NULL,
    "soul" INTEGER NOT NULL,
    "town_id" INTEGER NOT NULL,
    "posx" INTEGER NOT NULL,
    "posy" INTEGER NOT NULL,
    "posz" INTEGER NOT NULL,
    "conditions" BYTEA NOT NULL,
    "cap" INTEGER NOT NULL,
    "sex" INTEGER NOT NULL,
    "lastlogin" BIGINT NOT NULL,
    "lastip" INTEGER NOT NULL,
    "save" BOOLEAN NOT NULL,
    "skull" INTEGER NOT NULL,
    "skulltime" INTEGER NOT NULL,
    "rank_id" INTEGER NOT NULL,
    "guildnick" TEXT NOT NULL,
    "lastlogout" BIGINT NOT NULL,
    "blessings" INTEGER NOT NULL,
    "pvp_blessing" BOOLEAN NOT NULL,
    "balance" BIGINT NOT NULL,
    "stamina" BIGINT NOT NULL,
    "direction" INTEGER NOT NULL,
    "loss_experience" INTEGER NOT NULL,
    "loss_mana" INTEGER NOT NULL,
    "loss_skills" INTEGER NOT NULL,
    "loss_containers" INTEGER NOT NULL,
    "loss_items" INTEGER NOT NULL,
    "premend" INTEGER NOT NULL,
    "online" BOOLEAN NOT NULL,
    "marriage" INTEGER NOT NULL,
    "promotion" INTEGER NOT NULL,
    "deleted" INTEGER NOT NULL,
    "description" TEXT NOT NULL,
    "old_name" TEXT,
    "hidden" BOOLEAN NOT NULL,
    "worldtransfer" INTEGER,
    "created" INTEGER,
    "nick_verify" INTEGER,
    "comment" TEXT,
    "rep" INTEGER NOT NULL,
    "ip" TEXT NOT NULL,
    "offlinetraining_time" INTEGER NOT NULL,
    "offlinetraining_skill" INTEGER NOT NULL,
    "broadcasting" INTEGER NOT NULL,
    "viewers" INTEGER NOT NULL,

    CONSTRAINT "players_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "players_name_key" ON "players"("name");

-- AddForeignKey
ALTER TABLE "players" ADD CONSTRAINT "players_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
